version: '3.7'

services:
  realsense-ready:
    container_name: orbslam3
    image: 568/orbslam3
    restart: always
    privileged: true
    volumes:
      - ./dataset/P002/kitti:/media/P002/kitti    # Modify this to mount the dataset path
      - /tmp/.X11-unix:/tmp/.X11-unix     # For orb-ready only, give access to X11
    ports:
      - "8087:8087"                       # Inherited from realsense-ready
    environment:
      - DISPLAY=$DISPLAY                  # Inherited from realsense-ready
      - QT_X11_NO_MITSHM=1                # Inherited from realsense-ready
    stdin_open: true                      # For orb-ready only, equivalent to "docker run -i"
    tty: true                             # For orb-ready only, equivalent to "docker run -t"

    deploy:                               # For orb-ready only, in response to what(): Pangolin X11: Failed to create an OpenGL context
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']             # This ID may change on different machines : `lshw -c display` for more info
              capabilities: [gpu]
